export const data = [
  {
    id: "1",
    title: "Book Title 1",
    writer: "Writer 1",
    coverImage: "cover1.jpg",
    price: 55,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "2",
    title: "Book Title 2",
    writer: "Writer 2",
    coverImage: "cover1.jpg",
    price: 40,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "3",
    title: "Book Title 3",
    writer: "Writer 3",
    coverImage: "cover1.jpg",
    price: 83,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "4",
    title: "Book Title 4",
    writer: "Writer 4",
    coverImage: "cover1.jpg",
    price: 21,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "5",
    title: "Book Title 5",
    writer: "Writer 5",
    coverImage: "cover1.jpg",
    price: 8,
    tags: ["fiction", "novel", "science"],
  },
];
